export const mockCreators = [
  {
    id: 1,
    name: 'Alexander Ray',
    username: 'alexrayart',
    salesInfo: '42 sales on 12.5ETH',
    avatar: 'https://picsum.photos/80/80?1',
  },
  {
    id: 2,
    name: 'Elena Mist',
    username: 'mistygirl',
    salesInfo: '18 sales on 5.2ETH',
    avatar: 'https://picsum.photos/80/80?2',
  },
  {
    id: 3,
    name: 'Marcus Void',
    username: 'voidwalker',
    salesInfo: '105 sales on 88ETH',
    avatar: 'https://picsum.photos/80/80?3',
  },
  {
    id: 4,
    name: 'Sofia Bloom',
    username: 'bloomdigital',
    salesInfo: '34 sales on 15.4ETH',
    avatar: 'https://picsum.photos/80/80?4',
  },
  {
    id: 5,
    name: 'Dmitry Neon',
    username: 'neonrider',
    salesInfo: '67 sales on 32ETH',
    avatar: 'https://picsum.photos/80/80?5',
  },
  {
    id: 6,
    name: 'Luna Spark',
    username: 'sparkyluna',
    salesInfo: '12 sales on 2.8ETH',
    avatar: 'https://picsum.photos/80/80?6',
  },
  {
    id: 7,
    name: 'Victor Glitch',
    username: 'glitchmaster',
    salesInfo: '89 sales on 45.6ETH',
    avatar: 'https://picsum.photos/80/80?7',
  },
  {
    id: 8,
    name: 'Anna Ether',
    username: 'etherqueen',
    salesInfo: '5 sales on 1.2ETH',
    avatar: 'https://picsum.photos/80/80?8',
  },
  {
    id: 9,
    name: 'Ivan Pixel',
    username: 'pixelperfect',
    salesInfo: '204 sales on 112ETH',
    avatar: 'https://picsum.photos/80/80?9',
  },
  {
    id: 10,
    name: 'Sarah Cyber',
    username: 'cyberpunk88',
    salesInfo: '56 sales on 22.4ETH',
    avatar: 'https://picsum.photos/80/80?10',
  },
]
